name: freebsd

on: [ push, pull_request ]

jobs:
  clang:
    runs-on: macos-latest # until https://github.com/actions/runner/issues/385
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD VM
      uses: vmactions/freebsd-vm@v0.1.5 # aka FreeBSD 13.0
      with:
        usesh: true
        prepare: |
          pkg install -y meson pkgconf gtkmm30 nlohmann-json
          pkg install -y gtk-layer-shell
        run: |
          meson setup _build
          meson compile -C _build
