name: ubuntu

on:
  push:
    paths:
      - "**.cpp"
      - "**.h"
  pull_request:
    paths:
      - "**.cpp"
      - "**.h"

jobs:
  clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install meson pkgconf libgtkmm-3.0-dev nlohmann-json3-dev libgtk-layer-shell-dev clang gcc
    - name: Setup clang build
      env:
        CXX: clang++
      run: meson setup clang_build
    - name: Setup gcc build
      env:
        CXX: g++
      run: meson setup gcc_build
    - name: Build with clang
      run: ninja -C clang_build
    - name: Build with gcc
      run: ninja -C gcc_build
